### ISSUE TITLE
DB: ADD SEED DATA - Add all seed data to backend for users, songs, comments, likes

### ISSUE THREAD

**Issue by BrandonKMoore** [bcjumpman/Music_Haze#2]
- [x] Songs
- [x] Likes
- [x] Comments

**Comment by bcjumpman** [comment]
While working on the songs seed data, I ran into the error: sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Song->songs, expression 'Comment' failed to locate a name ('Comment'). If this is a class name, consider adding this relationship() to the <class 'app.models.song.Song'> class after both dependent classes have been defined.

Im thinking this is due to the order in which things are created, I was wondering if we should rename our seed data to ensure they get pulled correctly. The code that I was using has been pushed to my branch. I'll look this over with fresh eyes in the am.

**Comment by bcjumpman** [comment]
Seed data for likes, comments and songs has been completed and uploaded to dev branch.

**Comment by bcjumpman** [comment]
Once approved by the group, let's push to main for deployment.
